stages:
  - build
  - test
  - docker

variables:
  DOCKER_DRIVER: overlay2
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  DOCKER_TAG: latest
  REGISTRY: $CI_REGISTRY
  IMAGE_TAG: $REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME

cache:
  key: "$CI_COMMIT_REF_SLUG"
  paths:
    - .gradle/

build_and_test_user:
  stage: build
  image: gradle:8-jdk21-corretto
  script:
    - ./gradlew clean build
  artifacts:
    paths:
      - user_microservice/build/libs/*.jar

build_and_test_reservation:
  stage: build
  image: gradle:8-jdk21-corretto
  script:
    - ./gradlew clean build
  artifacts:
    paths:
      - reservation_microservice/build/libs/*.jar

build_and_test_location:
  stage: build
  image: gradle:8-jdk21-corretto
  script:
    - ./gradlew clean build
  artifacts:
    paths:
      - location_microservice/build/libs/*.jar

build_and_test_gateway:
  stage: build
  image: gradle:8-jdk21-corretto
  script:
    - ./gradlew clean build
  artifacts:
    paths:
      - api_gateway/build/libs/*.jar

build_api_gateway:
  stage: docker
  image: docker
  script:
    - cd api_gateway
    - |
      if [[ -n "$CI_COMMIT_TAG" ]]; then
        DOCKER_TAG="$CI_COMMIT_TAG"
      else
        DOCKER_TAG=latest
      fi
      echo "Building and pushing Docker image with tag: $DOCKER_TAG"

    - docker build -t $IMAGE_TAG/api_gateway:$DOCKER_TAG .
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $REGISTRY
    - docker push $IMAGE_TAG/api_gateway:$DOCKER_TAG
  only:
    - main
    - tags

build_location_microservice:
  stage: docker
  image: docker
  script:
    - cd location_microservice
    - |
      if [[ -n "$CI_COMMIT_TAG" ]]; then
        DOCKER_TAG="$CI_COMMIT_TAG"
      else
        DOCKER_TAG=latest
      fi
      echo "Building and pushing Docker image with tag: $DOCKER_TAG"

    - docker build -t $IMAGE_TAG/location_microservice:$DOCKER_TAG .
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $REGISTRY
    - docker push $IMAGE_TAG/location_microservice:$DOCKER_TAG
  only:
    - main
    - tags

build_reservation_microservice:
  stage: docker
  image: docker
  script:
    - cd reservation_microservice
    - |
      if [[ -n "$CI_COMMIT_TAG" ]]; then
        DOCKER_TAG="$CI_COMMIT_TAG"
      else
        DOCKER_TAG=latest
      fi
      echo "Building and pushing Docker image with tag: $DOCKER_TAG"

    - docker build -t $IMAGE_TAG/reservation_microservice:$DOCKER_TAG .
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $REGISTRY
    - docker push $IMAGE_TAG/reservation_microservice:$DOCKER_TAG
  only:
    - main
    - tags

build_user_microservice:
  stage: docker
  image: docker
  script:
    - cd user_microservice
    - |
      if [[ -n "$CI_COMMIT_TAG" ]]; then
        DOCKER_TAG="$CI_COMMIT_TAG"
      else
        DOCKER_TAG=latest
      fi
      echo "Building and pushing Docker image with tag: $DOCKER_TAG"

    - docker build -t $IMAGE_TAG/user_microservice:$DOCKER_TAG .
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $REGISTRY
    - docker push $IMAGE_TAG/user_microservice:$DOCKER_TAG
  only:
    - main
    - tags