services:
  location-service:
    image: gitlab.polytech.umontpellier.fr:5050/alexandre.deloire01/camping-microservices-app/location_microservice:latest
    container_name: location_ms-prod
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://location_db:5432/location_db
      - SPRING_DATASOURCE_USERNAME=location_user
      - SPRING_DATASOURCE_PASSWORD=location_pass
      - KAFKA_BROKER_URL=kafka:9092
    depends_on:
      - kafka

  reservation-service:
    image: gitlab.polytech.umontpellier.fr:5050/alexandre.deloire01/camping-microservices-app/reservation_microservice:latest
    container_name: reservation_ms-prod
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://reservation_db:5432/reservation_db
      - SPRING_DATASOURCE_USERNAME=reservation_user
      - SPRING_DATASOURCE_PASSWORD=reservation_pass
      - KAFKA_BROKER_URL=kafka:9092
    depends_on:
      - kafka

  user-service:
    image: gitlab.polytech.umontpellier.fr:5050/alexandre.deloire01/camping-microservices-app/user_microservice:latest
    container_name: user_ms-prod
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://user_db:5432/user_db
      - SPRING_DATASOURCE_USERNAME=user_user
      - SPRING_DATASOURCE_PASSWORD=user_pass
      - KAFKA_BROKER_URL=kafka:9092
    depends_on:
      - kafka

  api-gateway:
    image: gitlab.polytech.umontpellier.fr:5050/alexandre.deloire01/camping-microservices-app/api_gateway:latest
    container_name: api_gateway-prod
    ports:
      - "8083:8083"
    depends_on:
      - location-service
      - reservation-service
      - user-service

  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
    depends_on:
      - zookeeper

  location_db:
    image: postgres:alpine
    container_name: location_db
    environment:
      - POSTGRES_DB=location_db
      - POSTGRES_USER=location_user
      - POSTGRES_PASSWORD=location_pass
    volumes:
      - location_db_data:/var/lib/postgresql/data

  reservation_db:
    image: postgres:alpine
    container_name: reservation_db
    environment:
      - POSTGRES_DB=reservation_db
      - POSTGRES_USER=reservation_user
      - POSTGRES_PASSWORD=reservation_pass
    volumes:
      - reservation_db_data:/var/lib/postgresql/data

  user_db:
    image: postgres:alpine
    container_name: user_db
    environment:
      - POSTGRES_DB=user_db
      - POSTGRES_USER=user_user
      - POSTGRES_PASSWORD=user_pass
    volumes:
      - user_db_data:/var/lib/postgresql/data

volumes:
  location_db_data:
  reservation_db_data:
  user_db_data:
