services:
  location-service:
    image: location_microservice-image
    container_name: location_ms
    build:
      context: ./location_microservice
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://location_db:5432/location_db
      - SPRING_DATASOURCE_USERNAME=location_user
      - SPRING_DATASOURCE_PASSWORD=location_pass
      - KAFKA_BROKER_URL=kafka:9092
    depends_on:
      - kafka

  reservation-service:
    image: reservation_microservice-image
    container_name: reservation_ms
    build:
      context: ./reservation_microservice
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://reservation_db:5432/reservation_db
      - SPRING_DATASOURCE_USERNAME=reservation_user
      - SPRING_DATASOURCE_PASSWORD=reservation_pass
      - KAFKA_BROKER_URL=kafka:9092
    depends_on:
      - kafka

  user-service:
    image: user_microservice-image
    container_name: user_ms
    build:
      context: ./user_microservice
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://user_db:5432/user_db
      - SPRING_DATASOURCE_USERNAME=user_user
      - SPRING_DATASOURCE_PASSWORD=user_pass
      - KAFKA_BROKER_URL=kafka:9092
    depends_on:
      - kafka

  api-gateway:
    image: api_gateway-image
    container_name: api_gateway
    build:
      context: ./api_gateway
    ports:
      - "8083:8083"
    depends_on:
      - location-service
      - reservation-service
      - user-service

  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper

  location_db:
    image: postgres:alpine
    container_name: location_db
    environment:
      - POSTGRES_DB=location_db
      - POSTGRES_USER=location_user
      - POSTGRES_PASSWORD=location_pass
    ports:
      - "5434:5432"
    volumes:
      - location_db_data:/var/lib/postgresql/data

  reservation_db:
    image: postgres:alpine
    container_name: reservation_db
    environment:
      - POSTGRES_DB=reservation_db
      - POSTGRES_USER=reservation_user
      - POSTGRES_PASSWORD=reservation_pass
    ports:
      - "5435:5432"
    volumes:
      - reservation_db_data:/var/lib/postgresql/data

  user_db:
    image: postgres:alpine
    container_name: user_db
    environment:
      - POSTGRES_DB=user_db
      - POSTGRES_USER=user_user
      - POSTGRES_PASSWORD=user_pass
    ports:
      - "5436:5432"
    volumes:
      - user_db_data:/var/lib/postgresql/data

volumes:
  location_db_data:
  reservation_db_data:
  user_db_data:
